app/api/urls.py
from django.urls import path
from rest_framework.authtoken import views as authviews
from api import views

app_name = 'api'
urlpatterns = [

    # ------------------ AUTH --------------------------- #
    path('api-token-auth/', authviews.obtain_auth_token),

    # ------------------ METHODS --------------------------- #
    path('empresas/', views.empresas),
    path('contacts/', views.contacts),
    path('typeofcontacts/', views.typeofcontacts),
    path('economicdata/', views.economicdata),
    path('projects/', views.projects),
    path('invoices/', views.invoices),
    path('assistances/', views.assistances),
    path('line/', views.line),

]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fevama/', include('fevama.urls')),
    path('api/', include('api.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

app/fevama/urls.py
from django.urls import path
from .views import PasswordsChangeView
from . import views

from fevama import views

app_name = 'fevama'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('password/', PasswordsChangeView.as_view(template_name="fevama/change-password.html"), name="password"),
    path('password_success/', views.password_success, name="password_success"),

    # -------- CUADROS DE MANDO -------- #
    path('management_index/', views.management_index, name="management_index"),

    # -------- EMPRESAS -------- #
    path('projects_index/', views.projects_index, name="projects_index"),

    # EMPRESA
    path('empresas_index/', views.empresas_index, name="empresas_index"),
    path('empresa_create/', views.empresa_create, name="empresa_create"),
    path('empresa_createItem/', views.empresa_createItem, name="empresa_createItem"),
    path('empresa_deleteItem/', views.empresa_deleteItem, name="empresa_deleteItem"),
    path('empresa_modify/<id>', views.empresa_modify, name="empresa_modify"),
    path('empresa_modifyItem/', views.empresa_modifyItem, name="empresa_modifyItem"),
    
    # CONTACT
    path('contact/', views.contact_index, name="contact_index"),
    path('contact_create/', views.contact_create, name="contact_create"),
    path('contact_createItem/', views.contact_createItem, name="contact_createItem"),
    path('contact_deleteItem/', views.contact_deleteItem, name="contact_deleteItem"),
    path('contact_modify/<id>', views.contact_modify, name="contact_modify"),
    path('contact_modifyItem/', views.contact_modifyItem, name="contact_modifyItem"),

    # TYPE OF CONTACT
    path('typeofcontact_index/', views.typeofcontact_index, name="typeofcontact_index"),
    path('typeofcontact_showAll/', views.typeofcontact_showAll, name="typeofcontact_showAll"),
    path('typeofcontact_create/', views.typeofcontact_create, name="typeofcontact_create"),
    path('typeofcontact_createItem/', views.typeofcontact_createItem, name="typeofcontact_createItem"),
    path('typeofcontact_deleteItem/', views.typeofcontact_deleteItem, name="typeofcontact_deleteItem"),
    path('typeofcontact_modify/<id>', views.typeofcontact_modify, name="typeofcontact_modify"),
    path('typeofcontact_modifyItem/', views.typeofcontact_modifyItem, name="typeofcontact_modifyItem"),
    
    # ECONOMIC DATA
    path('economicdata_index/', views.economicdata_index, name="economicdata_index"),
    path('economicdata_create/', views.economicdata_create, name="economicdata_create"),
    path('economicdata_createItem/', views.economicdata_createItem, name="economicdata_createItem"),
    path('economicdata_modify/<id>', views.economicdata_modify, name="economicdata_modify"),
    path('economicdata_modifyItem/', views.economicdata_modifyItem, name="economicdata_modifyItem"),
    path('economicdata_deleteItem/', views.economicdata_deleteItem, name="economicdata_deleteItem"),


    # GRAPHS
    path('graphs_index/', views.graphs_index, name="graphs_index"),
    path('empresa_getdatagraph/', views.empresa_getdatagraph, name="empresa_getdatagraph"),
    path('empresa_compare/', views.empresa_compare, name="empresa_compare"),

    path('anualdata_graphs/', views.anualdata_graphs, name="anualdata_graphs"),
    path('anualdata_getdatagraph/', views.anualdata_getdatagraph, name="anualdata_getdatagraph"),

    path('line_graphs/', views.line_graphs, name="line_graphs"),
    path('line_getdatagraph/', views.line_getdatagraph, name="line_getdatagraph"), 

    # -------- SUBVENCIONES -------- #
    path('ayudas_index/', views.ayudas_index, name="ayudas_index"),

    # PROYECTOS
    path('project_index/', views.project_index, name="project_index"),
    path('project_deleteItem/', views.project_deleteItem, name="project_deleteItem"),
    path('project_create/', views.project_create, name="project_create"),
    path('project_createItem/', views.project_createItem, name="project_createItem"),
    path('project_modify/<id>', views.project_modify, name="project_modify"),
    path('project_modifyItem/', views.project_modifyItem, name="project_modifyItem"),

    # FACTURAS
    path('invoice_index/', views.invoice_index, name="invoice_index"),
    path('invoice_deleteItem/', views.invoice_deleteItem, name="invoice_deleteItem"),
    path('invoice_create/', views.invoice_create, name="invoice_create"),
    path('invoice_createItem/', views.invoice_createItem, name="invoice_createItem"),
    path('invoice_modify/<id>', views.invoice_modify, name="invoice_modify"),
    path('invoice_modifyItem/', views.invoice_modifyItem, name="invoice_modifyItem"),

    # AYUDAS
    path('assistance_index/', views.assistance_index, name="assistance_index"),
    path('assistance_deleteItem/', views.assistance_deleteItem, name="assistance_deleteItem"),
    path('assistance_create/', views.assistance_create, name="assistance_create"),
    path('assistance_createItem/', views.assistance_createItem, name="assistance_createItem"),
    path('assistance_modify/<id>', views.assistance_modify, name="assistance_modify"),
    path('assistance_modifyItem/', views.assistance_modifyItem, name="assistance_modifyItem"),
    path('assistance_details/<id>', views.assistance_details, name="assistance_details"),
    

    # LINEA DE AYUDAS
    path('line_index/', views.line_index, name="line_index"),
    path('line_deleteItem/', views.line_deleteItem, name="line_deleteItem"),
    path('line_create/', views.line_create, name="line_create"),
    path('line_createItem/', views.line_createItem, name="line_createItem"),
    path('line_modify/<id>', views.line_modify, name="line_modify"),
    path('line_modifyItem/', views.line_modifyItem, name="line_modifyItem"),
    
    # ACTUACIÓN
    path('act_index/', views.act_index, name="act_index"),
    path('act_deleteItem/', views.act_deleteItem, name="act_deleteItem"),
    path('act_create/', views.act_create, name="act_create"),
    path('act_createItem/', views.act_createItem, name="act_createItem"),
    path('act_modify/<id>', views.act_modify, name="act_modify"),
    path('act_modifyItem/', views.act_modifyItem, name="act_modifyItem"),

    # -------- RECURSOS HUMANOS -------- #
    path('planificacion_index/', views.planificacion_index, name="planificacion_index"),

    # SOLICITANTES
    path('applicant_index/', views.applicant_index, name="applicant_index"),
    path('applicant_deleteItem/', views.applicant_deleteItem, name="applicant_deleteItem"),
    path('applicant_create/', views.applicant_create, name="applicant_create"),
    path('applicant_createItem/', views.applicant_createItem, name="applicant_createItem"),
    path('applicant_modify/<id>', views.applicant_modify, name="applicant_modify"),
    path('applicant_modifyItem/', views.applicant_modifyItem, name="applicant_modifyItem"),

    # ORGANISMO
    path('organism_index/', views.organism_index, name="organism_index"),
    path('organism_deleteItem/', views.organism_deleteItem, name="organism_deleteItem"),
    path('organism_create/', views.organism_create, name="organism_create"), 
    path('organism_createItem/', views.organism_createItem, name="organism_createItem"),
    path('organism_modify/<id>', views.organism_modify, name="organism_modify"),
    path('organism_modifyItem/', views.organism_modifyItem, name="organism_modifyItem"),

    # SITUACIÓN
    path('situation_index/', views.situation_index, name="situation_index"),
    path('situation_deleteItem/', views.situation_deleteItem, name="situation_deleteItem"),
    path('situation_create/', views.situation_create, name="situation_create"), 
    path('situation_createItem/', views.situation_createItem, name="situation_createItem"),
    path('situation_modify/<id>', views.situation_modify, name="situation_modify"),
    path('situation_modifyItem/', views.situation_modifyItem, name="situation_modifyItem"),

    # CONVOCATORIA
    path('announcement_index/', views.announcement_index, name="announcement_index"),
    path('announcement_deleteItem/', views.announcement_deleteItem, name="announcement_deleteItem"),
    path('announcement_create/', views.announcement_create, name="announcement_create"),
    path('announcement_createItem/', views.announcement_createItem, name="announcement_createItem"),
    path('announcement_modify/<id>', views.announcement_modify, name="announcement_modify"),
    path('announcement_modifyItem/', views.announcement_modifyItem, name="announcement_modifyItem"),


    # -------- NOTIFICACIONES -------- #
    path('notificaciones_index/', views.notificaciones_index, name="notificaciones_index"),

    path('alerts_index/', views.alerts_index, name="alerts_index"),
    path('alert_deleteItem/', views.alert_deleteItem, name="alert_deleteItem"),

    path('notifications_index/', views.notifications_index, name="notifications_index"),
    path('notification_create/', views.notification_create, name="notification_create"),
    path('notification_deleteItem/', views.notification_deleteItem, name="notification_deleteItem"),
    
    

    # -------- BASE DE DATOS -------- #
    path('bd_index/', views.bd_index, name="bd_index"),
    path('BDconfiguration_index/', views.BDconfiguration_index, name="BDconfiguration_index"),
    path('execute_backup/', views.execute_backup, name="execute_backup"),
    path('backup_upload/', views.backup_upload, name="backup_upload"),
    path('restore_database/', views.restore_database, name="restore_database"),
    path('modify_bdconfig/', views.modify_bdconfig, name="modify_bdconfig"),
    path('change_bcfile/', views.change_bcfile, name="change_bcfile"),
    path('last_backup/', views.last_backup, name="last_backup"),
    path('last_economicData/', views.last_economicData, name="last_economicData"),
    path('last_contacts/', views.last_contacts, name="last_contacts"),
    
    path('cleanBD_index/', views.cleanBD_index, name="cleanBD_index"),

app/fevama/templates/fevama/act_list.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load static %}
{% load fontawesome_5 %}
{% fontawesome_5_static %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<style>
.centrado {
  margin: 1rem;
  padding: 1rem;
}
.search-box{
  width: fit-content;
  height: fit-content;
  position: relative;
}
.input-search{
  height: 50px;
  width: 50px;
  border-style: none;
  padding: 10px;
  font-size: 18px;
  letter-spacing: 2px;
  outline: none;
  border-radius: 25px;
  transition: all .5s ease-in-out;
  background-color:  #d7dadd;
  padding-right: 40px;
  color:rgb(12, 12, 12);
}
.input-search::placeholder{
  color:rgb(7, 7, 7);
  font-size: 18px;
  letter-spacing: 2px;
  font-weight: 100;
}
.btn-search{
  width: 50px;
  height: 50px;
  border-style: none;
  font-size: 20px;
  font-weight: bold;
  outline: none;
  cursor: pointer;
  border-radius: 50%;
  position: absolute;
  right: 0px;
  color:#070707 ;
  background-color:transparent;
  pointer-events: painted;  
}
.btn-search:focus ~ .input-search{
  width: 300px;
  border-radius: 0px;
  background-color: transparent;
  border-bottom:1px solid rgba(0, 0, 0, 0.5);
  transition: all 500ms cubic-bezier(0, 0.110, 0.35, 2);
}
.input-search:focus{
  width: 300px;
  border-radius: 0px;
  background-color: transparent;
  border-bottom:1px solid rgba(88, 87, 87, 0.5);
  transition: all 500ms cubic-bezier(0, 0.110, 0.35, 2);
}
</style>
<body style="background-color: #efefef;">
<div class="centrado">
    <legend style="margin-top: 20px; text-align: center;">
        <i class="fas fa-align-justify"></i> {% trans 'ACTUACIÓN' %}
    </legend>
    <hr/>
    <div class="col-md-12" style="display: flex;">
        <div class="col-md-1"></div>
        <div class="col-md-1" style="margin-top: 5px;">
            <a id="btn-back" class="btn btn-outline-secondary" href="{% url 'fevama:ayudas_index' %}">
                {% fa5_icon 'long-arrow-alt-left' 'fas' %} {% trans 'Volver' %}
            </a>
        </div>
        <div class="col-md-2" style="margin-top: 5px;">
            <a id="btn-back" class="btn btn-outline-secondary" href="{% url 'fevama:act_create' %}">
                {% fa5_icon 'plus' 'fas' %} {% trans 'Crear nueva Actuación' %}
            </a>
        </div>
        <div class="col-md-5"></div>
        <div class="col-md-2">
            <div class="search-box pull-left">
                <button class="btn-search"><i class="fas fa-search"></i></button>
                <input type="text" class="input-search" placeholder="Buscar en la tabla..." id="search">
            </div>
        </div>
    </div>
    <table class="table table-striped table-hover" style="margin-top: 20px;text-align: center;" id="mytable">
        <thead>
            <tr style="background-color: rgb(133, 172, 172);">
                <td><b>ID</b></td>
                <td><b>ACTUACIÓN</b></td>
                <td><b>ACCIONES</b></td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
                {% for act in object_list %}
                <tr>
                    <td>{{act.id}}</td>
                    <td>{{act.name}}</td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="{% url 'fevama:act_modify' act.id %}"> EDITAR </a>
                        <a id="btn-delete" class="btn btn-danger btn-sm" onclick="deleteItem({{act.id}})"> ELIMINAR </a>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
</div>
</body>
<script>
    // Write on keyup event of keyword input element
    $(document).ready(function(){
        $("#search").keyup(function(){
        _this = this;
        // Show only matching TR, hide rest of them
        $.each($("#mytable tbody tr"), function() {
        if($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
            $(this).hide();
        else
            $(this).show();
        });
        });
    });
    function deleteItem(id){
        if(confirm('{% trans "Estás seguro de eliminar esta actuación?" %}'))
        {
            $.ajax({
                url: '{% url "fevama:act_deleteItem" %}',
                data:  {
                    'data': id,
                },
                dataType: 'json',
                success: function (data) {
                    location.reload(true)
                },
                error: function (data) {
                    document.getElementById("btn-delete").className = "btn btn-danger btn btn-block btnBootstrapping";
                    document.getElementById("btn-delete").innerHTML="ERROR"; 
                    location.reload(true)
                },
            });
        }
    }
</script>
{% endblock %}

app/fevama/templates/fevama/economicdata_list.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load static %}
{% load fontawesome_5 %}
{% fontawesome_5_static %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<style>
.centrado {
  margin: 1rem;
  padding: 1rem;
}
.search-box{
  width: fit-content;
  height: fit-content;
  position: relative;
}
.input-search{
  height: 50px;
  width: 50px;
  border-style: none;
  padding: 10px;
  font-size: 18px;
  letter-spacing: 2px;
  outline: none;
  border-radius: 25px;
  transition: all .5s ease-in-out;
  background-color:  #d7dadd;
  padding-right: 40px;
  color:rgb(12, 12, 12);
}
.input-search::placeholder{
  color:rgb(7, 7, 7);
  font-size: 18px;
  letter-spacing: 2px;
  font-weight: 100;
}
.btn-search{
  width: 50px;
  height: 50px;
  border-style: none;
  font-size: 20px;
  font-weight: bold;
  outline: none;
  cursor: pointer;
  border-radius: 50%;
  position: absolute;
  right: 0px;
  color:#070707 ;
  background-color:transparent;
  pointer-events: painted;  
}
.btn-search:focus ~ .input-search{
  width: 300px;
  border-radius: 0px;
  background-color: transparent;
  border-bottom:1px solid rgba(0, 0, 0, 0.5);
  transition: all 500ms cubic-bezier(0, 0.110, 0.35, 2);
}
.input-search:focus{
  width: 300px;
  border-radius: 0px;
  background-color: transparent;
  border-bottom:1px solid rgba(88, 87, 87, 0.5);
  transition: all 500ms cubic-bezier(0, 0.110, 0.35, 2);
}
/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}
</style>
<body style="background-color: #efefef;">
<div class="centrado">
    <legend style="margin-top: 20px; text-align: center;">
        <i class="fas fa-coins"></i> {% trans 'Datos Económicos' %}
    </legend>
    <hr/>
    <div class="col-md-12" style="display: flex;">
        <div class="col-md-1"></div>
        <div class="col-md-1" style="margin-top: 5px;">
            <a id="btn-back" class="btn btn-outline-secondary" href="{% url 'fevama:projects_index' %}">
                {% fa5_icon 'long-arrow-alt-left' 'fas' %} {% trans 'Volver' %}
            </a>
        </div>
        <div class="col-md-2" style="margin-top: 5px;">
            <a id="btn-back" class="btn btn-outline-secondary" href="{% url 'fevama:economicdata_create' %}">
                {% fa5_icon 'plus' 'fas' %} {% trans 'Crear nuevo registro' %}
            </a>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-2" style="margin-top: 5px;text-align: center;">
            <button id="myBtn" class="btn btn-outline-secondary">Ordenar</button>
        </div>
        <div class="col-md-2">
        <!-- <input type="text" class="form-control pull-right" style="width:auto" id="search" placeholder="Buscar en la tabla..."> -->
            <div class="search-box pull-left">
                <button class="btn-search"><i class="fas fa-search"></i></button>
                <input type="text" class="input-search" placeholder="Buscar en la tabla..." id="search">
            </div>
        </div>
    </div>
    <table class="table table-striped table-hover" style="margin-top: 20px;text-align: center;" id="mytable">
        <thead>
            <tr style="background-color: rgb(133, 172, 172);">
                <td><b>ID</b></td>
                <td><b>EMPRESA</b></td>
                <td><b>AÑO</b></td>
                <td><b>TRABAJADORES</b></td>
                <td><b>CIFRA NEGOCIO</b></td>
                <td><b>ACCIONES</b></td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
                {% for economic_data in object_list %}
                <tr>
                    <td>{{economic_data.id}}</td>
                    <td>{{economic_data.empresa.name}}</td>
                    <td>{{economic_data.year}}</td>
                    <td>{{economic_data.workers}}</td>
                    <td>{{economic_data.data}}€</td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="{% url 'fevama:economicdata_modify' economic_data.id %}"> EDITAR </a>
                        <a id="btn-delete" class="btn btn-danger btn-sm" onclick="borrar({{economic_data.id}})"> ELIMINAR </a>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    {% if lenght >= 20 %}
    <div class="centrado" style="display: flex; justify-content: center;">
        <a id="btn-all" class="btn btn-outline-secondary" onclick="showmore()">
            {% fa5_icon 'plus' 'fas' %} {% trans 'Mostrar más' %}
        </a>
    </div>
    {% endif %}
</div>
<!-- The Modal -->
<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <p>Opciones:</p>
      <p>De mayor a menor AÑO</p>
      <p>De menor a mayor AÑO</p>
      <p>De mayor a menor CIFRA NEGOCIO</p>
      <p>De menor a mayor CIFRA NEGOCIO</p>
    </div>
</div>

</body>
<script>
    var modal = document.getElementById("myModal");
    var btn = document.getElementById("myBtn");
    var span = document.getElementsByClassName("close")[0];
    btn.onclick = function() {
        modal.style.display = "block";
    }
    span.onclick = function() {
        modal.style.display = "none";
    }
    window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
    }

    // Write on keyup event of keyword input element
    $(document).ready(function(){
        $("#search").keyup(function(){
        _this = this;
        // Show only matching TR, hide rest of them
        $.each($("#mytable tbody tr"), function() {
        if($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
            $(this).hide();
        else
            $(this).show();
        });
        });
    });

    function borrar(id){
        if(confirm('{% trans "Estás seguro de eliminar este registro?" %}'))
        {
            $.ajax({
                url: '{% url "fevama:economicdata_deleteItem" %}',
                data:  {
                    'data': id
                },
                dataType: 'json',
                success: function (data) {
                    location.reload(true)
                },
                error: function (data) {
                    document.getElementById("btn-delete").className = "btn btn-danger btn btn-block btnBootstrapping";
                    document.getElementById("btn-delete").innerHTML="ERROR"; 
                    location.reload(true)
                },
            });
        }
    }
    function showmore(){
        $.ajax({
                url: '{% url "fevama:typeofcontact_showAll" %}',
                data:  {},
                dataType: 'json',
                success: function (data) {
                    console.log(data["data"]);
                    data = data["data"]
                    for (var i=0; i< data.length; i++){
                        var button = "<a id=edit"+ i + "> EDITAR </a>";
                        var button2 = "<a id=eliminar"+ i + "> ELIMINAR </a>";
                        $('#tbody').append("<tr><td>" + data[i].id + "</td><td>" + data[i].type +"</td><td>" + 
                            button + " " + button2
                            );
                        check= "edit"+i;
                        check1= "eliminar"+i;
                        var edit_button = document.getElementById(check);
                        edit_button.classList.add("btn", "btn-primary", "btn-sm");
                        delete_button = document.getElementById(check1);
                        delete_button.classList.add("btn", "btn-danger", "btn-sm");
                        id = data[i].id;
                        delete_button.onclick = function() {
                            if(confirm('{% trans "Estás seguro de eliminar este tipo de contacto? Se eliminarán todos los contactos que tengan este tipo" %}'))
                                {
                                    $.ajax({
                                        url: '{% url "fevama:typeofcontact_deleteItem" %}',
                                        data:  {
                                            'data': id,
                                        },
                                        dataType: 'json',
                                        success: function (data) {
                                            location.reload(true);
                                        },
                                        error: function (data) {
                                            document.getElementById("btn-delete").className = "btn btn-danger btn btn-block btnBootstrapping";
                                            document.getElementById("btn-delete").innerHTML="ERROR"; 
                                            location.reload(true);
                                        },
                                    });
                                }
                        }
                    }
                    document.getElementById("btn-all").style = "display:none"
                    
                },
                error: function (data) {
                    console.log(data)
                    document.getElementById("btn-delete").className = "btn btn-danger btn btn-block btnBootstrapping";
                    document.getElementById("btn-delete").innerHTML="ERROR"; 
                },
            });  
    }
</script>
{% endblock %}

app/fevama/templates/fevama/parametros_index.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load fontawesome_5 %}
{% fontawesome_5_static %}

{% block content %}
<style>
    .index-button
    {
        width:95%;
        border-radius: 25%;
        background-color:#FFFFFF;
        border: 2px solid #000000;
        padding: 30px 30px;
        margin:5px 5px 5px 5px;
    }
    .index-button:hover
    {
        width:95%;
        border-radius: 25%;
        background-color:#d4d0d0;
        border: 2px solid #b6a9a9;
        padding: 30px 30px;
        margin:5px 5px 5px 5px;
    }
</style>
<link rel="stylesheet" type="text/css" href="../../../../../static/admin/css/dashboard.css">
<body style="background-color: #efefef;">
    <div id="content" style="margin-left: 20px; margin-right: 20px;">
        <legend style="margin-top: 20px;">
            <i class="fas fa-user-cog"></i> {% trans 'Parámetros' %}
        </legend>
        <hr/>
        <table class="table-responsive">
            <tr>
            </tr>
            <tr>
                <td height="75" width="140">
                    <a class="btn btn-block btn-default index-button" href="{% url 'fevama:users_index' %}" title="{% trans 'Usuarios' %}">
                        {% fa5_icon 'users' 'fas fa-3x' %}
                    </a>
                </td>         
            </tr>
                <td align="center">{% trans "Usuarios" %}</td>
            <tr>
        </table>
    </div>
</body>
{% endblock %}